---
apiVersion: "v1"
kind: "Template"
labels:
  template: "redhatmsa-with-hawkular-apm"
metadata:
  name: "redhatmsa"
  annotations:
    openshift.io/display-name: "Red Hat Hello World MSA"
    description: "The Red Hat Hello World MSA (Microservice Architecture) (with Hawkular APM)."
objects:
- apiVersion: "v1"
  kind: "ServiceAccount"
  metadata:
    name: "turbine"
- apiVersion: "v1"
  kind: "DeploymentConfig"
  metadata:
    labels:
      app: "turbine-server"
    name: "turbine-server"
  spec:
    replicas: "1"
    selector:
      app: "turbine-server"
      deploymentconfig: "turbine-server"
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          app: "turbine-server"
          deploymentconfig: "turbine-server"
      spec:
        containers:
        - name: "turbine-server"
          image: "fabric8/turbine-server:1.0.28"
          env:
          - name: "DT_CLUSTER_ID"
            value: "Turbine"
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          ports:
          - containerPort: 8080
            protocol: "TCP"
          resources: {}
        serviceAccountName: "turbine"
  status: {}
- apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      app: "turbine-server"
    name: "turbine-server"
  spec:
    ports:
    - name: "8080-tcp"
      port: 8080
      protocol: "TCP"
      targetPort: 8080
    selector:
      app: "turbine-server"
      deploymentconfig: "turbine-server"
  status:
    loadBalancer: {}
- apiVersion: "v1"
  kind: "Route"
  metadata:
    name: "turbine-server"
  spec:
    port:
      targetPort: 8080
    to:
      kind: "Service"
      name: "turbine-server"
- apiVersion: "v1"
  kind: "ServiceAccount"
  metadata:
    name: "ribbon"
- apiVersion: "v1"
  kind: "DeploymentConfig"
  metadata:
    labels:
      app: "hystrix-dashboard"
    name: "hystrix-dashboard"
  spec:
    replicas: "1"
    selector:
      app: "hystrix-dashboard"
      deploymentconfig: "hystrix-dashboard"
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          app: "hystrix-dashboard"
          deploymentconfig: "hystrix-dashboard"
      spec:
        containers:
        - name: "hystrix-dashboard"
          image: "fabric8/hystrix-dashboard:1.0.28"
          env:
          - name: "DT_CLUSTER_ID"
            value: "Hystrix"
          ports:
          - containerPort: 8080
            protocol: "TCP"
          resources: {}
        serviceAccountName: "turbine"
  status: {}
- apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      app: "hystrix-dashboard"
    name: "hystrix-dashboard"
  spec:
    ports:
    - name: "8080-tcp"
      port: 8080
      protocol: "TCP"
      targetPort: 8080
    selector:
      app: "hystrix-dashboard"
      deploymentconfig: "hystrix-dashboard"
  status:
    loadBalancer: {}
- apiVersion: "v1"
  kind: "Route"
  metadata:
    name: "hystrix-dashboard"
  spec:
    port:
      targetPort: 8080
    to:
      kind: "Service"
      name: "hystrix-dashboard"
- apiVersion: "v1"
  kind: "DeploymentConfig"
  metadata:
    labels:
      app: "frontend"
      hystrix.enabled: "true"
    name: "frontend"
  spec:
    replicas: "1"
    selector:
      app: "frontend"
      deploymentconfig: "frontend"
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          app: "frontend"
          hystrix.enabled: "true"
          deploymentconfig: "frontend"
      spec:
        containers:
        - name: "frontend"
          image: "metmajer/redhatmsa-frontend"
          env:
          - name: "DT_CLUSTER_ID"
            value: "Red Hat MSA: Frontend"
          - name: "OS_PROJECT"
            value: "${OS_PROJECT}"
          - name: "OS_SUBDOMAIN"
            value: "${OS_SUBDOMAIN}"
          - name: "ENABLE_HYSTRIX"
            value: "true"
          - name: "ENABLE_ZIPKIN"
            value: "false"
          ports:
          - containerPort: 8080
            protocol: "TCP"
          resources: {}
  status: {}
- apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      app: "frontend"
      hystrix.enabled: "true"
    name: "frontend"
  spec:
    ports:
    - name: "8080-tcp"
      port: 8080
      protocol: "TCP"
      targetPort: 8080
    selector:
      app: "frontend"
      deploymentconfig: "frontend"
  status:
    loadBalancer: {}
- apiVersion: "v1"
  kind: "Route"
  metadata:
    name: "frontend"
  spec:
    to:
      kind: "Service"
      name: "frontend"
- apiVersion: "v1"
  kind: "DeploymentConfig"
  metadata:
    labels:
      app: "api-gateway"
      hystrix.enabled: "true"
    name: "api-gateway"
  spec:
    replicas: "1"
    selector:
      app: "api-gateway"
      deploymentconfig: "api-gateway"
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          app: "api-gateway"
          deploymentconfig: "api-gateway"
          hystrix.enabled: "true"
      spec:
        containers:
        - name: "api-gateway"
          image: "metmajer/redhatmsa-api-gateway:hawkular-apm"
          env:
          - name: "AB_ENABLED"
            value: "jolokia"
          - name: "DT_CLUSTER_ID"
            value: "Red Hat MSA: API Gateway"
          - name: "HAWKULAR_APM_URI"
            value: "http://${HAWKULAR_APM_SERVICE_NAME}-${HAWKULAR_APM_PROJECT_NAME}.${OS_SUBDOMAIN}"
          - name: "HAWKULAR_APM_USERNAME"
            value: "${HAWKULAR_APM_ADMIN_USERNAME}"
          - name: "HAWKULAR_APM_PASSWORD"
            value: "${HAWKULAR_APM_ADMIN_PASSWORD}"
          - name: "ZIPKIN_SERVER_URL"
            value: "http://${HAWKULAR_APM_SERVICE_NAME}-${HAWKULAR_APM_PROJECT_NAME}.${OS_SUBDOMAIN}"
          ports:
          - containerPort: 8080
            protocol: "TCP"
          - containerPort: 8778
            protocol: "TCP"
          - containerPort: 9779
            protocol: "TCP"
          resources: {}
        volumes:
        - name: hawkular-openshift-agent
          configMap:
            name: my-hosa-config
  status: {}
- apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      app: "api-gateway"
      hystrix.enabled: "true"
    name: "api-gateway"
  spec:
    ports:
    - name: "8080-tcp"
      port: 8080
      protocol: "TCP"
      targetPort: 8080
    - name: "8778-tcp"
      port: 8778
      protocol: "TCP"
      targetPort: 8778
    - name: "9779-tcp"
      port: 9779
      protocol: "TCP"
      targetPort: 9779
    selector:
      app: "api-gateway"
      deploymentconfig: "api-gateway"
  status:
    loadBalancer: {}
- apiVersion: "v1"
  kind: "Route"
  metadata:
    name: "api-gateway"
  spec:
    port:
      targetPort: 8080
    to:
      kind: "Service"
      name: "api-gateway"
- apiVersion: "v1"
  kind: "Route"
  metadata:
    name: "jolokia-api-gateway"
  spec:
    path: "/jolokia/"
    port:
      targetPort: 8778
    to:
      kind: "Service"
      name: "api-gateway"
- apiVersion: "v1"
  kind: "DeploymentConfig"
  metadata:
    labels:
      app: "aloha"
      hystrix.enabled: "true"
    name: "aloha"
  spec:
    replicas: "1"
    selector:
      app: "aloha"
      deploymentconfig: "aloha"
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          app: "aloha"
          deploymentconfig: "aloha"
          hystrix.enabled: "true"
      spec:
        containers:
        - name: "aloha"
          image: "metmajer/redhatmsa-aloha:hawkular-apm"
          env:
          - name: "AB_ENABLED"
            value: "jolokia"
          - name: "DT_CLUSTER_ID"
            value: "Red Hat MSA: Aloha"
          - name: "HAWKULAR_APM_URI"
            value: "http://${HAWKULAR_APM_SERVICE_NAME}-${HAWKULAR_APM_PROJECT_NAME}.${OS_SUBDOMAIN}"
          - name: "HAWKULAR_APM_USERNAME"
            value: "${HAWKULAR_APM_ADMIN_USERNAME}"
          - name: "HAWKULAR_APM_PASSWORD"
            value: "${HAWKULAR_APM_ADMIN_PASSWORD}"
          - name: "ZIPKIN_SERVER_URL"
            value: "http://${HAWKULAR_APM_SERVICE_NAME}-${HAWKULAR_APM_PROJECT_NAME}.${OS_SUBDOMAIN}"
          ports:
          - containerPort: 8080
            protocol: "TCP"
          - containerPort: 8778
            protocol: "TCP"
          - containerPort: 9779
            protocol: "TCP"
          resources: {}
  status: {}
- apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      app: "aloha"
      hystrix.enabled: "true"
    name: "aloha"
  spec:
    ports:
    - name: "8080-tcp"
      port: 8080
      protocol: "TCP"
      targetPort: 8080
    - name: "8778-tcp"
      port: 8778
      protocol: "TCP"
      targetPort: 8778
    - name: "9779-tcp"
      port: 9779
      protocol: "TCP"
      targetPort: 9779
    selector:
      app: "aloha"
      deploymentconfig: "aloha"
  status:
    loadBalancer: {}
- apiVersion: "v1"
  kind: "Route"
  metadata:
    name: "aloha"
  spec:
    port:
      targetPort: 8080
    to:
      kind: "Service"
      name: "aloha"
- apiVersion: "v1"
  kind: "Route"
  metadata:
    name: "jolokia-aloha"
  spec:
    path: "/jolokia/"
    port:
      targetPort: 8778
    to:
      kind: "Service"
      name: "aloha"
- apiVersion: "v1"
  kind: "DeploymentConfig"
  metadata:
    labels:
      app: "bonjour"
      hystrix.enabled: "true"
    name: "bonjour"
  spec:
    replicas: "1"
    selector:
      app: "bonjour"
      deploymentconfig: "bonjour"
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          app: "bonjour"
          deploymentconfig: "bonjour"
          hystrix.enabled: "true"
      spec:
        containers:
        - name: "bonjour"
          image: "metmajer/redhatmsa-bonjour"
          env:
          - name: "DT_CLUSTER_ID"
            value: "Red Hat MSA: Bonjour"
          - name: "ZIPKIN_SERVER_URL"
            value: "http://${HAWKULAR_APM_SERVICE_NAME}-${HAWKULAR_APM_PROJECT_NAME}.${OS_SUBDOMAIN}"
          ports:
          - containerPort: 8080
            protocol: "TCP"
          resources: {}
  status: {}
- apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      app: "bonjour"
      hystrix.enabled: "true"
    name: "bonjour"
  spec:
    ports:
    - name: "8080-tcp"
      port: 8080
      protocol: "TCP"
      targetPort: 8080
    selector:
      app: "bonjour"
      deploymentconfig: "bonjour"
  status:
    loadBalancer: {}
- apiVersion: "v1"
  kind: "Route"
  metadata:
    name: "bonjour"
  spec:
    to:
      kind: "Service"
      name: "bonjour"
- apiVersion: v1
  kind: "DeploymentConfig"
  metadata:
    labels:
      app: "hola"
      hystrix.enabled: "true"
    name: "hola"
  spec:
    replicas: "1"
    selector:
      app: "hola"
      deploymentconfig: "hola"
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          app: "hola"
          deploymentconfig: "hola"
          hystrix.enabled: "true"
      spec:
        containers:
        - name: "hola"
          image: "metmajer/redhatmsa-hola:hawkular-apm"
          env:
          - name: "AB_ENABLED"
            value: "jolokia"
          - name: "DT_CLUSTER_ID"
            value: "Red Hat MSA: Hola"
          - name: "HAWKULAR_APM_URI"
            value: "http://${HAWKULAR_APM_SERVICE_NAME}-${HAWKULAR_APM_PROJECT_NAME}.${OS_SUBDOMAIN}"
          - name: "HAWKULAR_APM_USERNAME"
            value: "${HAWKULAR_APM_ADMIN_USERNAME}"
          - name: "HAWKULAR_APM_PASSWORD"
            value: "${HAWKULAR_APM_ADMIN_PASSWORD}"
          - name: "ZIPKIN_SERVER_URL"
            value: "http://${HAWKULAR_APM_SERVICE_NAME}-${HAWKULAR_APM_PROJECT_NAME}.${OS_SUBDOMAIN}"
          ports:
          - containerPort: 8080
            protocol: "TCP"
          - containerPort: 8778
            protocol: "TCP"
          - containerPort: 9779
            protocol: "TCP"
          resources: {}
  status: {}
- apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      app: "hola"
      hystrix.enabled: "true"
    name: "hola"
  spec:
    ports:
    - name: "8080-tcp"
      port: 8080
      protocol: "TCP"
      targetPort: 8080
    - name: "8778-tcp"
      port: 8778
      protocol: "TCP"
      targetPort: 8778
    - name: "9779-tcp"
      port: 9779
      protocol: "TCP"
      targetPort: 9779
    selector:
      app: "hola"
      deploymentconfig: "hola"
  status:
    loadBalancer: {}
- apiVersion: "v1"
  kind: "Route"
  metadata:
    name: "hola"
  spec:
    port:
      targetPort: 8080
    to:
      kind: "Service"
      name: "hola"
- apiVersion: "v1"
  kind: "Route"
  metadata:
    name: "jolokia-hola"
  spec:
    path: "/jolokia/"
    port:
      targetPort: 8778
    to:
      kind: "Service"
      name: "hola"
- apiVersion: "v1"
  kind: "DeploymentConfig"
  metadata:
    labels:
      app: "ola"
      hystrix.enabled: "true"
    name: "ola"
  spec:
    replicas: "1"
    selector:
      app: "ola"
      deploymentconfig: "ola"
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          app: "ola"
          deploymentconfig: "ola"
          hystrix.enabled: "true"
      spec:
        containers:
        - name: "ola"
          image: "metmajer/redhatmsa-ola:hawkular-apm"
          env:
          - name: "AB_ENABLED"
            value: "jolokia"
          - name: "DT_CLUSTER_ID"
            value: "Red Hat MSA: Ola"
          - name: "HAWKULAR_APM_URI"
            value: "http://${HAWKULAR_APM_SERVICE_NAME}-${HAWKULAR_APM_PROJECT_NAME}.${OS_SUBDOMAIN}"
          - name: "HAWKULAR_APM_USERNAME"
            value: "${HAWKULAR_APM_ADMIN_USERNAME}"
          - name: "HAWKULAR_APM_PASSWORD"
            value: "${HAWKULAR_APM_ADMIN_PASSWORD}"
          - name: "ZIPKIN_SERVER_URL"
            value: "http://${HAWKULAR_APM_SERVICE_NAME}-${HAWKULAR_APM_PROJECT_NAME}.${OS_SUBDOMAIN}"
          ports:
          - containerPort: 8080
            protocol: "TCP"
          - containerPort: 8778
            protocol: "TCP"
          - containerPort: 9779
            protocol: "TCP"
          resources: {}
  status: {}
- apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      app: "ola"
      hystrix.enabled: "true"
    name: "ola"
  spec:
    ports:
    - name: "8080-tcp"
      port: 8080
      protocol: "TCP"
      targetPort: 8080
    - name: "8778-tcp"
      port: 8778
      protocol: "TCP"
      targetPort: 8778
    - name: "9779-tcp"
      port: 9779
      protocol: "TCP"
      targetPort: 9779
    selector:
      app: "ola"
      deploymentconfig: "ola"
  status:
    loadBalancer: {}
- apiVersion: "v1"
  kind: "Route"
  metadata:
    name: "ola"
  spec:
    port:
      targetPort: 8080
    to:
      kind: "Service"
      name: "ola"
- apiVersion: "v1"
  kind: "Route"
  metadata:
    name: "jolokia-ola"
  spec:
    path: "/jolokia/"
    port:
      targetPort: 8778
    to:
      kind: "Service"
      name: "ola"
parameters:
- name: "OS_PROJECT"
  description: "The name of the project."
  value: "OS_PROJECT"
  required: true
- name: "OS_SUBDOMAIN"
  description: "The OpenShift master's domain for server routes."
  value: "OS_SUBDOMAIN"
  required: true
- name: "HAWKULAR_APM_SERVICE_NAME"
  description: "The name of the Hawkular APM Service."
  value: "HAWKULAR_APM_SERVICE_NAME"
  required: true
- name: "HAWKULAR_APM_PROJECT_NAME"
  description: "The name of the Hawkular APM Service's project."
  value: "OS_PROJECT"
  required: true
- name: "HAWKULAR_APM_ADMIN_USERNAME"
  description: "The username for the user with administrative privileges."
  value: "admin"
  required: true
- name: "HAWKULAR_APM_ADMIN_PASSWORD"
  description: "The password for the user with administrative privileges."
  value: "password"
